const teamData = {
  SCORP: [
    {
      name: "Anteneh Girma",
      title: "General Assistant",
      phone: "+251984955544",
      email: "antenehgirma444@gmail.com",
      imgSrc: "/scorp-official1.png",
    },
    {
      name: "Feven Birhanu",
      title: "General Assistant",
      phone: "0938752610",
      email: "pheobeberhanu@gmail.com",
      imgSrc: "/scorp-official6.png",
    },
    {
      name: "Fikir Belete",
      title: "General Assistant",
      phone: "+251989964541",
      email: "gfikirbelete@gmail.com",
      imgSrc: "/scorp-official4.png",
    },
    {
      name: "Jochebed Kinfemichael",
      title: "Activity Coordinator for people with disabilities",
      phone: "+251 96 204 6517",
      email: "jokikgn@gmail.com",
      imgSrc: "/scorp-official3.png",
    },
    {
      name: "Maramawit Belachew",
      title: "Activity Coordinator for People for People with Disabilities",
      phone: "+251949187419",
      email: "ethma21@gmail.com",
      imgSrc: "/scorp-official7.png",
    },
    {
      name: "Ibtisam Ramadan",
      title: "Activity Coordinator for GBV and Women's Right",
      phone: "+251906631854",
      email: "ibtisamramadan48@gmail.com",
      imgSrc: "/scorp-official2.png",
    },
    {
      name: "Dlyana Kedir",
      title: "PRC",
      phone: "+251967942483",
      email: "dlaynakedir91@gmail.com",
      imgSrc: "/scorp-official8.png",
    },
  ],
  SCOPH: [
    {
      name: "Mintesnot Meskele",
      title: "National Officer for Public Health",
      phone: "+251942213298",
      email: "mintesnot.meskele@gmail.com",
      imgSrc: "/scoph-official1.png",
    },
    {
      name: "AMANUEL TADESSE",
      title: "General Assistant for Administration",
      phone: "+251911747604",
      email: "amanitadeabi@gmail.com",
      imgSrc: "/scoph-official2.png",
    },
    {
      name: "HURIYUMA ABDULJELIL",
      title: "Capacity Building Development Assistant",
      phone: "+251920032647",
      email: "abdulhummi@gmail.com",
      imgSrc: "/scoph-official3.png",
    },
    {
      name: "FISSEHA MULUGETA",
      title: "Members Engagement Development Assistant",
      phone: "+251973388897",
      email: "fishmulugeta@gmail.com",
      imgSrc: "/scoph-official4.png",
    },
    {
      name: "EBAWAK GUDETA",
      title: "Capacity Building Development Assistant",
      phone: "+251943829117",
      email: "ebawakguden@gmail.com",
      imgSrc: "/scoph-official5.png",
    },
    {
      name: "IMAN KEDIR",
      title: "General Assistant for Exchange",
      phone: "+251940073378",
      email: "Imankedir.4@gmail.com",
      imgSrc: "/scoph-official6.png",
    },
    {
      name: "LEUL MEKONNEN",
      title: "Public Relations and Communication Development Assistant",
      phone: "+2519610977088",
      email: "Leulmekonen321@gmail.com",
      imgSrc: "/scoph-official7.png",
    },
    {
      name: "NATNAEL WORKU",
      title: "Public Relations and Communication Development Assistant",
      phone: "+251938957575",
      email: "Natnaelworku777@gmial.com",
      imgSrc: "/scoph-official8.png",
    },
  ],
  SCORA: [
    {
      name: "Abenezer Woyesa",
      title: "NORA",
      phone: "+251 93 251 2454",
      email: "abenezerwoyesa01@gmail.com",
      imgSrc: "/scora-official1.png",
    },
    {
      name: "Feven Kassaw",
      title: "General Secretary",
      phone: "+251 92 286 1404",
      email: "kassawfeven@gmail.com",
      imgSrc: "/scora-official2.png",
    },
    {
      name: "Meklit Kibkab",
      title: "External Affairs Assistant",
      phone: "+251 92 332 8284",
      email: "meklitkibkabmelaku@gmail.com",
      imgSrc: "/scora-official3.png",
    },
    {
      name: "Bemnet Ashenafi",
      title: "Public Relations and Communication Development Assistant",
      phone: "0973-111-480",
      email: "bemnet.ashenafi@aau.edu.et",
      imgSrc: "/scora-official4.png",
    },
    {
      name: "Essete Gashawtena",
      title: "Member Engagement and Development Assistant",
      phone: "+251 911 687 055",
      email: "eseteg08@gmail.com",
      imgSrc: "/scora-official5.png",
    },
    {
      name: "Nigist Bekele",
      title: "Capacity Building Development Assistant",
      phone: "+251 92 900 1604",
      email: "nigistgbekele@gmail.com",
      imgSrc: "/scora-official6.png",
    },
    {
      name: "Nejat Musema",
      title: "Capacity Building Development Assistant",
      phone: "+251 96 262 7662",
      email: "nejatzenu@gmail.com",
      imgSrc: "/scora-official7.png",
    },
  ],
  Officials: [
    {
      name: "Dr. Keno Kumera",
      title: "Supervising Council",
      phone: "+251940180547",
      email: "kenokume77@gmail.com",
      imgSrc: "/officials1.png",
    },
    {
      name: "Dr. Tsinat Mulugeta ",
      title: "National Supervising Council Member 2022/24",
      phone: "+251925318506",
      email: "mulugetatsinat@gmail.com",
      imgSrc: "/officials7.png",
    },
    {
      name: "Maramawit Messay Mekonnen",
      title: "National Exchange Officer",
      phone: "+251929143198",
      email: "maramawitmessay@yahoo.com",
      imgSrc: "/officials3.png",
    },
    {
      name: "Abenezer Woyesa Turilo",
      title: "National Officer for SCORA",
      phone: "+251932512454",
      email: "abenezerwoyesa01@gmail.com ",
      imgSrc: "/officials5.png",
    },
    {
      name: "Dr. Seblewengel Birku Kebebew",
      title: "Position Title",
      phone: "+251923513409",
      email: "seblewongelbirku@gmail.com",
      imgSrc: "/officials6.png",
    },
    {
      name: "Abigael Abiy Mesfin",
      title: "NORE",
      phone: "0983399368",
      email: "abiyabigael@gmail.com",
      imgSrc: "/officials4.png",
    },
    {
      name: "Mintesnot Meskele Anchebe",
      title: "National public health officer(NPO)",
      phone: "+251942213298",
      email: "mintesnot.meskele@gmail.com",
      imgSrc: "/officials2.png",
    },
    {
      name: "Yared Kiros Alema",
      title: "National President 23/24",
      phone: "0968604855",
      email: "yaredkalema@gmail.com",
      imgSrc: "/officials8.png",
    },
    {
      name: "Eman Jemal Mohammed",
      title: "Vice President for Activities",
      phone: "0973112576",
      email: "emanj742@gmail.com",
      imgSrc: "/officials10.png",
    },
  ],
};

export default teamData;
